import type { ValueType } from '@/types';

export type AggregationType = 'sum' | 'avg' | 'last';

export interface KnownMetric {
  key: string;
  displayName: string;
  type: ValueType;
  unit?: string;
  aliases?: string[];
  color: string;
  emoji: string;
  aggregation: AggregationType; // how multiple same-day logs combine
}

export const KNOWN_METRICS: KnownMetric[] = [
  {
    key: 'sleep',
    displayName: 'Sleep',
    type: 'number',
    unit: 'h',
    color: '#007aff',
    emoji: '🌙',
    aggregation: 'last',
    aliases: [
      'slept',
      'sleeping',
      'nap',
      'napped',
      'napping',
      'kip',
      'crashed',
      'snooze',
      'snoozed',
      'dozed',
      'doze',
      'rest',
      'rested',
      'resting',
      'bedtime',
      'shut eye',
      'shuteye',
      'hours sleep',
      'hrs sleep',
      'hours of sleep',
      'night sleep',
      'sleep time',
    ],
  },
  {
    key: 'workout',
    displayName: 'Workout',
    type: 'boolean',
    unit: undefined,
    color: '#30d158',
    emoji: '💪',
    aggregation: 'last',
    aliases: [
      'gym',
      'exercise',
      'exercised',
      'exercising',
      'training',
      'trained',
      'lift',
      'lifted',
      'lifting',
      'leg',
      'legs',
      'chest',
      'back',
      'shoulders',
      'shoulder',
      'arms',
      'biceps',
      'triceps',
      'core',
      'abs',
      'worked out',
      'hit gym',
      'hit the gym',
      'weights',
      'weight training',
      'sweat',
      'grind',
      'hiit',
      'cardio',
      'circuit',
      'crossfit',
      'push day',
      'pull day',
      'leg day',
      'chest day',
      'back day',
      'arms day',
      'bodybuilding',
      'strength',
      'gainz',
      'gains',
    ],
  },
  {
    key: 'protein',
    displayName: 'Protein',
    type: 'number',
    unit: 'g',
    color: '#ff9f0a',
    emoji: '🥩',
    aggregation: 'sum',
    aliases: [
      'proteins',
      'whey',
      'protein shake',
      'shake',
      'grams protein',
      'protein intake',
      'protein count',
      'daily protein',
      'macros protein',
    ],
  },
  {
    key: 'mood',
    displayName: 'Mood',
    type: 'number',
    unit: '/10',
    color: '#bf5af2',
    emoji: '😊',
    aggregation: 'avg',
    aliases: [
      'vibe',
      'vibes',
      'emotions',
      'emotion',
      'mental',
      'mental health',
      'happiness',
      'happy',
      'sad',
      'meh',
      'blah',
      'moody',
      'spirits',
      'mindset',
      'great',
    ],
  },
  {
    key: 'water',
    displayName: 'Water',
    type: 'number',
    unit: 'L',
    color: '#40cbe0',
    emoji: '💧',
    aggregation: 'sum',
    aliases: [
      'hydration',
      'hydrated',
      'fluids',
      'fluid',
      'h2o',
      'drank water',
      'drinking water',
      'water intake',
      'liters water',
      'litres water',
      'cups water',
      'glasses water',
      'glasses of water',
      'cups of water',
    ],
  },
  {
    key: 'steps',
    displayName: 'Steps',
    type: 'number',
    unit: 'k',
    color: '#ff375f',
    emoji: '👟',
    aggregation: 'sum',
    aliases: [
      'walked',
      'walking',
      'walk',
      'steps taken',
      'step count',
      'stepcount',
      'pedometer',
      'paced',
      'daily steps',
      'total steps',
    ],
  },
  {
    key: 'weight',
    displayName: 'Weight',
    type: 'number',
    unit: 'kg',
    color: '#ff9f0a',
    emoji: '⚖️',
    aggregation: 'last',
    aliases: [
      'bodyweight',
      'body weight',
      'bw',
      'mass',
      'weighed',
      'scale',
      'scale weight',
      'heaviness',
      'body mass',
      'current weight',
      'morning weight',
    ],
  },
  {
    key: 'meditation',
    displayName: 'Meditation',
    type: 'number',
    unit: 'min',
    color: '#40cbe0',
    emoji: '🧘',
    aggregation: 'sum',
    aliases: [
      'meditated',
      'meditating',
      'mindfulness',
      'mindful',
      'breathwork',
      'breathing exercise',
      'breathing',
      'breathe',
      'calm',
      'wim hof',
      'zen',
      'centered',
      'grounded',
      'body scan',
      'visualization',
      'guided meditation',
    ],
  },
  {
    key: 'reading',
    displayName: 'Reading',
    type: 'number',
    unit: 'min',
    color: '#ffd60a',
    emoji: '📚',
    aggregation: 'sum',
    aliases: [
      'read',
      'reads',
      'books',
      'book',
      'reading time',
      'pages',
      'page',
      'studied',
      'study',
      'studying',
      'learning',
      'learned',
      'literature',
      'nonfiction',
      'fiction',
    ],
  },
  {
    key: 'caffeine',
    displayName: 'Caffeine',
    type: 'number',
    unit: 'mg',
    color: '#a2845e',
    emoji: '☕',
    aggregation: 'sum',
    aliases: [
      'coffee',
      'coffees',
      'espresso',
      'chai',
      'tea',
      'teas',
      'matcha',
      'latte',
      'lattes',
      'cappuccino',
      'americano',
      'cold brew',
      'brew',
      'green tea',
      'black tea',
      'energy drink',
      'red bull',
      'redbull',
      'monster',
      'preworkout',
      'pre-workout',
      'pre workout',
      'pre workouts',
      'cup of coffee',
      'cup of tea',
      'cups of coffee',
    ],
  },
  {
    key: 'calories',
    displayName: 'Calories',
    type: 'number',
    unit: 'kcal',
    color: '#ff453a',
    emoji: '🍽️',
    aggregation: 'sum',
    aliases: [
      'cal',
      'cals',
      'kcal',
      'calorie',
      'caloric',
      'intake',
      'food intake',
      'total calories',
      'daily calories',
      'calorie count',
      'eaten',
      'consumed',
      'nutrition',
      'diet',
      'macros',
    ],
  },
  {
    key: 'run',
    displayName: 'Run',
    type: 'number',
    unit: 'km',
    color: '#30d158',
    emoji: '🏃',
    aggregation: 'sum',
    aliases: [
      'running',
      'ran',
      'jog',
      'jogged',
      'jogging',
      'sprint',
      'sprinted',
      'sprinting',
      'treadmill',
      'outdoor run',
      'morning run',
      '5k',
      '10k',
      'half marathon',
      'marathon',
      'pace run',
      'tempo run',
      'easy run',
    ],
  },
  {
    key: 'energy',
    displayName: 'Energy',
    type: 'number',
    unit: '/10',
    color: '#ffd60a',
    emoji: '⚡',
    aggregation: 'avg',
    aliases: [
      'energized',
      'energy level',
      'energy levels',
      'tired',
      'tiredness',
      'fatigue',
      'fatigued',
      'exhausted',
      'exhaustion',
      'drained',
      'sluggish',
      'lethargic',
      'lethargy',
      'alert',
      'awake',
      'wired',
      'crash',
      'crashed',
      'vigor',
      'vitality',
    ],
  },
  {
    key: 'stress',
    displayName: 'Stress',
    type: 'number',
    unit: '/10',
    color: '#ff453a',
    emoji: '😰',
    aggregation: 'avg',
    aliases: [
      'anxiety',
      'anxious',
      'stressed',
      'stressful',
      'overwhelmed',
      'tense',
      'tension',
      'burnout',
      'pressure',
      'worry',
      'worried',
      'worrying',
      'panic',
      'panicked',
      'nervous',
      'nervousness',
      'cortisol',
    ],
  },
  {
    key: 'screen',
    displayName: 'Screen Time',
    type: 'number',
    unit: 'h',
    color: '#636366',
    emoji: '📱',
    aggregation: 'sum',
    aliases: [
      'screen time',
      'screentime',
      'phone',
      'phone time',
      'device time',
      'scrolling',
      'scrolled',
      'social media',
      'doom scroll',
      'doom scrolling',
      'doomscrolling',
      'tv',
      'television',
      'netflix',
      'youtube',
      'instagram',
      'twitter',
      'tiktok',
      'online',
      'browsing',
    ],
  },
  {
    key: 'alcohol',
    displayName: 'Alcohol',
    type: 'boolean',
    unit: undefined,
    color: '#ff9f0a',
    emoji: '🍺',
    aggregation: 'last',
    aliases: [
      'drinks',
      'drinking',
      'drank',
      'booze',
      'boozy',
      'drunk',
      'tipsy',
      'buzzed',
      'beer',
      'beers',
      'wine',
      'wines',
      'whiskey',
      'whisky',
      'vodka',
      'spirits',
      'pint',
      'pints',
      'shots',
      'shot',
      'cocktail',
      'cocktails',
      'liquor',
      'gin',
      'rum',
      'tequila',
      'brandy',
      'champagne',
      'prosecco',
    ],
  },
];
